// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/api/proto/order/order.proto
//
// NOTE: 为了在没有 protoc 的环境中也能编译运行，本文件被直接提交到仓库中。

package orderpb

import (
	reflect "reflect"
	sync "sync"

	proto "google.golang.org/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Order struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VehicleId      string                 `protobuf:"bytes,3,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	DriverId       string                 `protobuf:"bytes,4,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Status         string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	BizTag         string                 `protobuf:"bytes,6,opt,name=biz_tag,json=bizTag,proto3" json:"biz_tag,omitempty"`
	Channel        string                 `protobuf:"bytes,7,opt,name=channel,proto3" json:"channel,omitempty"`
	PickupAddress  string                 `protobuf:"bytes,8,opt,name=pickup_address,json=pickupAddress,proto3" json:"pickup_address,omitempty"`
	DropoffAddress string                 `protobuf:"bytes,9,opt,name=dropoff_address,json=dropoffAddress,proto3" json:"dropoff_address,omitempty"`
	EstimatedPrice int64                  `protobuf:"varint,10,opt,name=estimated_price,json=estimatedPrice,proto3" json:"estimated_price,omitempty"`
	FinalPrice     int64                  `protobuf:"varint,11,opt,name=final_price,json=finalPrice,proto3" json:"final_price,omitempty"`
	Currency       string                 `protobuf:"bytes,12,opt,name=currency,proto3" json:"currency,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      int64                  `protobuf:"varint,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	AcceptedAt     int64                  `protobuf:"varint,15,opt,name=accepted_at,json=acceptedAt,proto3" json:"accepted_at,omitempty"`
	StartedAt      int64                  `protobuf:"varint,16,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt    int64                  `protobuf:"varint,17,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	CanceledAt     int64                  `protobuf:"varint,18,opt,name=canceled_at,json=canceledAt,proto3" json:"canceled_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_internal_api_proto_order_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}
func (x *Order) String() string { return protoimpl.X.MessageStringOf(x) }
func (*Order) ProtoMessage()    {}
func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_order_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*Order) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_order_order_proto_rawDescGZIP(), []int{0}
}

type CreateOrderRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VehicleId      string                 `protobuf:"bytes,2,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	DriverId       string                 `protobuf:"bytes,3,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	BizTag         string                 `protobuf:"bytes,4,opt,name=biz_tag,json=bizTag,proto3" json:"biz_tag,omitempty"`
	Channel        string                 `protobuf:"bytes,5,opt,name=channel,proto3" json:"channel,omitempty"`
	PickupAddress  string                 `protobuf:"bytes,6,opt,name=pickup_address,json=pickupAddress,proto3" json:"pickup_address,omitempty"`
	DropoffAddress string                 `protobuf:"bytes,7,opt,name=dropoff_address,json=dropoffAddress,proto3" json:"dropoff_address,omitempty"`
	EstimatedPrice int64                  `protobuf:"varint,8,opt,name=estimated_price,json=estimatedPrice,proto3" json:"estimated_price,omitempty"`
	Currency       string                 `protobuf:"bytes,9,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_internal_api_proto_order_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}
func (x *CreateOrderRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*CreateOrderRequest) ProtoMessage()    {}
func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_order_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_order_order_proto_rawDescGZIP(), []int{1}
}

type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_internal_api_proto_order_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}
func (x *CreateOrderResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*CreateOrderResponse) ProtoMessage()    {}
func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_order_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_order_order_proto_rawDescGZIP(), []int{2}
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_internal_api_proto_order_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}
func (x *GetOrderRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*GetOrderRequest) ProtoMessage()    {}
func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_order_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_order_order_proto_rawDescGZIP(), []int{3}
}

type GetOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderResponse) Reset() {
	*x = GetOrderResponse{}
	mi := &file_internal_api_proto_order_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}
func (x *GetOrderResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*GetOrderResponse) ProtoMessage()    {}
func (x *GetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_order_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_order_order_proto_rawDescGZIP(), []int{4}
}

type UpdateOrderStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderStatusRequest) Reset() {
	*x = UpdateOrderStatusRequest{}
	mi := &file_internal_api_proto_order_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}
func (x *UpdateOrderStatusRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*UpdateOrderStatusRequest) ProtoMessage()    {}
func (x *UpdateOrderStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_order_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*UpdateOrderStatusRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_order_order_proto_rawDescGZIP(), []int{5}
}

type UpdateOrderStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderStatusResponse) Reset() {
	*x = UpdateOrderStatusResponse{}
	mi := &file_internal_api_proto_order_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}
func (x *UpdateOrderStatusResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*UpdateOrderStatusResponse) ProtoMessage()    {}
func (x *UpdateOrderStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_order_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*UpdateOrderStatusResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_order_order_proto_rawDescGZIP(), []int{6}
}

type ListOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersRequest) Reset() {
	*x = ListOrdersRequest{}
	mi := &file_internal_api_proto_order_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}
func (x *ListOrdersRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*ListOrdersRequest) ProtoMessage()    {}
func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_order_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_order_order_proto_rawDescGZIP(), []int{7}
}

type ListOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersResponse) Reset() {
	*x = ListOrdersResponse{}
	mi := &file_internal_api_proto_order_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}
func (x *ListOrdersResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*ListOrdersResponse) ProtoMessage()    {}
func (x *ListOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_order_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*ListOrdersResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_order_order_proto_rawDescGZIP(), []int{8}
}

var File_internal_api_proto_order_order_proto protoreflect.FileDescriptor

var file_internal_api_proto_order_order_proto_rawDescOnce sync.Once
var file_internal_api_proto_order_order_proto_rawDesc []byte

var file_internal_api_proto_order_order_proto_rawDescGZIPOnce sync.Once
var file_internal_api_proto_order_order_proto_rawDescGZIPData []byte

func file_internal_api_proto_order_order_proto_rawDescInit() []byte {
	file_internal_api_proto_order_order_proto_rawDescOnce.Do(func() {
		fd := buildOrderFileDescriptorProto()
		b, _ := proto.Marshal(fd)
		file_internal_api_proto_order_order_proto_rawDesc = b
	})
	return file_internal_api_proto_order_order_proto_rawDesc
}

func file_internal_api_proto_order_order_proto_rawDescGZIP() []byte {
	file_internal_api_proto_order_order_proto_rawDescInit()
	file_internal_api_proto_order_order_proto_rawDescGZIPOnce.Do(func() {
		file_internal_api_proto_order_order_proto_rawDescGZIPData = protoimpl.X.CompressGZIP(file_internal_api_proto_order_order_proto_rawDesc)
	})
	return file_internal_api_proto_order_order_proto_rawDescGZIPData
}

var file_internal_api_proto_order_order_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_internal_api_proto_order_order_proto_goTypes = []any{
	(*Order)(nil),                     // 0: smartlinkdrive.order.v1.Order
	(*CreateOrderRequest)(nil),        // 1: smartlinkdrive.order.v1.CreateOrderRequest
	(*CreateOrderResponse)(nil),       // 2: smartlinkdrive.order.v1.CreateOrderResponse
	(*GetOrderRequest)(nil),           // 3: smartlinkdrive.order.v1.GetOrderRequest
	(*GetOrderResponse)(nil),          // 4: smartlinkdrive.order.v1.GetOrderResponse
	(*UpdateOrderStatusRequest)(nil),  // 5: smartlinkdrive.order.v1.UpdateOrderStatusRequest
	(*UpdateOrderStatusResponse)(nil), // 6: smartlinkdrive.order.v1.UpdateOrderStatusResponse
	(*ListOrdersRequest)(nil),         // 7: smartlinkdrive.order.v1.ListOrdersRequest
	(*ListOrdersResponse)(nil),        // 8: smartlinkdrive.order.v1.ListOrdersResponse
}

var file_internal_api_proto_order_order_proto_depIdxs = []int32{
	0, // 0: smartlinkdrive.order.v1.CreateOrderResponse.order:type_name -> smartlinkdrive.order.v1.Order
	0, // 1: smartlinkdrive.order.v1.GetOrderResponse.order:type_name -> smartlinkdrive.order.v1.Order
	0, // 2: smartlinkdrive.order.v1.UpdateOrderStatusResponse.order:type_name -> smartlinkdrive.order.v1.Order
	0, // 3: smartlinkdrive.order.v1.ListOrdersResponse.orders:type_name -> smartlinkdrive.order.v1.Order
	0, // [0:4] is the sub-list for field type_name
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for method output_type
}

func init() { file_internal_api_proto_order_order_proto_init() }
func file_internal_api_proto_order_order_proto_init() {
	if File_internal_api_proto_order_order_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_api_proto_order_order_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Order); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_proto_order_order_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CreateOrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_proto_order_order_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CreateOrderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_proto_order_order_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetOrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_proto_order_order_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetOrderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_proto_order_order_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateOrderStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_proto_order_order_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateOrderStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_proto_order_order_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*ListOrdersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_proto_order_order_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*ListOrdersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}

	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_api_proto_order_order_proto_rawDescInit(),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_api_proto_order_order_proto_goTypes,
		DependencyIndexes: file_internal_api_proto_order_order_proto_depIdxs,
		MessageInfos:      file_internal_api_proto_order_order_proto_msgTypes,
	}.Build()
	File_internal_api_proto_order_order_proto = out.File
	file_internal_api_proto_order_order_proto_rawDesc = nil
	file_internal_api_proto_order_order_proto_rawDescGZIPData = nil
	file_internal_api_proto_order_order_proto_goTypes = nil
	file_internal_api_proto_order_order_proto_depIdxs = nil
}

func buildOrderFileDescriptorProto() *descriptorpb.FileDescriptorProto {
	str := func(s string) *string { return &s }
	i32 := func(v int32) *int32 { return &v }
	label := func(v descriptorpb.FieldDescriptorProto_Label) *descriptorpb.FieldDescriptorProto_Label { return &v }
	typ := func(v descriptorpb.FieldDescriptorProto_Type) *descriptorpb.FieldDescriptorProto_Type { return &v }

	pkg := "smartlinkdrive.order.v1"
	name := "internal/api/proto/order/order.proto"
	syntax := "proto3"

	orderMsg := &descriptorpb.DescriptorProto{
		Name: str("Order"),
		Field: []*descriptorpb.FieldDescriptorProto{
			{Name: str("id"), Number: i32(1), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_STRING), JsonName: str("id")},
			{Name: str("user_id"), Number: i32(2), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_STRING), JsonName: str("userId")},
			{Name: str("vehicle_id"), Number: i32(3), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_STRING), JsonName: str("vehicleId")},
			{Name: str("driver_id"), Number: i32(4), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_STRING), JsonName: str("driverId")},
			{Name: str("status"), Number: i32(5), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_STRING), JsonName: str("status")},
			{Name: str("biz_tag"), Number: i32(6), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_STRING), JsonName: str("bizTag")},
			{Name: str("channel"), Number: i32(7), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_STRING), JsonName: str("channel")},
			{Name: str("pickup_address"), Number: i32(8), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_STRING), JsonName: str("pickupAddress")},
			{Name: str("dropoff_address"), Number: i32(9), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_STRING), JsonName: str("dropoffAddress")},
			{Name: str("estimated_price"), Number: i32(10), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_INT64), JsonName: str("estimatedPrice")},
			{Name: str("final_price"), Number: i32(11), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_INT64), JsonName: str("finalPrice")},
			{Name: str("currency"), Number: i32(12), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_STRING), JsonName: str("currency")},
			{Name: str("created_at"), Number: i32(13), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_INT64), JsonName: str("createdAt")},
			{Name: str("updated_at"), Number: i32(14), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_INT64), JsonName: str("updatedAt")},
			{Name: str("accepted_at"), Number: i32(15), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_INT64), JsonName: str("acceptedAt")},
			{Name: str("started_at"), Number: i32(16), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_INT64), JsonName: str("startedAt")},
			{Name: str("completed_at"), Number: i32(17), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_INT64), JsonName: str("completedAt")},
			{Name: str("canceled_at"), Number: i32(18), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_INT64), JsonName: str("canceledAt")},
		},
	}

	createReq := &descriptorpb.DescriptorProto{
		Name: str("CreateOrderRequest"),
		Field: []*descriptorpb.FieldDescriptorProto{
			{Name: str("user_id"), Number: i32(1), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_STRING), JsonName: str("userId")},
			{Name: str("vehicle_id"), Number: i32(2), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_STRING), JsonName: str("vehicleId")},
			{Name: str("driver_id"), Number: i32(3), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_STRING), JsonName: str("driverId")},
			{Name: str("biz_tag"), Number: i32(4), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_STRING), JsonName: str("bizTag")},
			{Name: str("channel"), Number: i32(5), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_STRING), JsonName: str("channel")},
			{Name: str("pickup_address"), Number: i32(6), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_STRING), JsonName: str("pickupAddress")},
			{Name: str("dropoff_address"), Number: i32(7), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_STRING), JsonName: str("dropoffAddress")},
			{Name: str("estimated_price"), Number: i32(8), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_INT64), JsonName: str("estimatedPrice")},
			{Name: str("currency"), Number: i32(9), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_STRING), JsonName: str("currency")},
		},
	}

	createResp := &descriptorpb.DescriptorProto{
		Name: str("CreateOrderResponse"),
		Field: []*descriptorpb.FieldDescriptorProto{
			{Name: str("order"), Number: i32(1), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_MESSAGE), TypeName: str(".smartlinkdrive.order.v1.Order"), JsonName: str("order")},
		},
	}

	getReq := &descriptorpb.DescriptorProto{
		Name: str("GetOrderRequest"),
		Field: []*descriptorpb.FieldDescriptorProto{
			{Name: str("id"), Number: i32(1), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_STRING), JsonName: str("id")},
		},
	}

	getResp := &descriptorpb.DescriptorProto{
		Name: str("GetOrderResponse"),
		Field: []*descriptorpb.FieldDescriptorProto{
			{Name: str("order"), Number: i32(1), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_MESSAGE), TypeName: str(".smartlinkdrive.order.v1.Order"), JsonName: str("order")},
		},
	}

	updateReq := &descriptorpb.DescriptorProto{
		Name: str("UpdateOrderStatusRequest"),
		Field: []*descriptorpb.FieldDescriptorProto{
			{Name: str("id"), Number: i32(1), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_STRING), JsonName: str("id")},
			{Name: str("status"), Number: i32(2), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_STRING), JsonName: str("status")},
		},
	}

	updateResp := &descriptorpb.DescriptorProto{
		Name: str("UpdateOrderStatusResponse"),
		Field: []*descriptorpb.FieldDescriptorProto{
			{Name: str("order"), Number: i32(1), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_MESSAGE), TypeName: str(".smartlinkdrive.order.v1.Order"), JsonName: str("order")},
		},
	}

	listReq := &descriptorpb.DescriptorProto{
		Name: str("ListOrdersRequest"),
		Field: []*descriptorpb.FieldDescriptorProto{
			{Name: str("user_id"), Number: i32(1), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_STRING), JsonName: str("userId")},
			{Name: str("status"), Number: i32(2), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_STRING), JsonName: str("status")},
			{Name: str("page"), Number: i32(3), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_INT32), JsonName: str("page")},
			{Name: str("page_size"), Number: i32(4), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_INT32), JsonName: str("pageSize")},
		},
	}

	listResp := &descriptorpb.DescriptorProto{
		Name: str("ListOrdersResponse"),
		Field: []*descriptorpb.FieldDescriptorProto{
			{Name: str("orders"), Number: i32(1), Label: label(descriptorpb.FieldDescriptorProto_LABEL_REPEATED), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_MESSAGE), TypeName: str(".smartlinkdrive.order.v1.Order"), JsonName: str("orders")},
			{Name: str("total"), Number: i32(2), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_INT64), JsonName: str("total")},
		},
	}

	svc := &descriptorpb.ServiceDescriptorProto{
		Name: str("OrderService"),
		Method: []*descriptorpb.MethodDescriptorProto{
			{Name: str("CreateOrder"), InputType: str(".smartlinkdrive.order.v1.CreateOrderRequest"), OutputType: str(".smartlinkdrive.order.v1.CreateOrderResponse")},
			{Name: str("GetOrder"), InputType: str(".smartlinkdrive.order.v1.GetOrderRequest"), OutputType: str(".smartlinkdrive.order.v1.GetOrderResponse")},
			{Name: str("UpdateOrderStatus"), InputType: str(".smartlinkdrive.order.v1.UpdateOrderStatusRequest"), OutputType: str(".smartlinkdrive.order.v1.UpdateOrderStatusResponse")},
			{Name: str("ListOrders"), InputType: str(".smartlinkdrive.order.v1.ListOrdersRequest"), OutputType: str(".smartlinkdrive.order.v1.ListOrdersResponse")},
		},
	}

	return &descriptorpb.FileDescriptorProto{
		Name:    &name,
		Package: &pkg,
		Syntax:  &syntax,
		Options: &descriptorpb.FileOptions{
			GoPackage: str("github.com/SmartLinkDrive/SmartLinkDrive/internal/api/proto/order;orderpb"),
		},
		MessageType: []*descriptorpb.DescriptorProto{
			orderMsg,
			createReq,
			createResp,
			getReq,
			getResp,
			updateReq,
			updateResp,
			listReq,
			listResp,
		},
		Service: []*descriptorpb.ServiceDescriptorProto{svc},
	}
}
