// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/api/proto/vehicle/vehicle.proto
//
// NOTE: This repository's development environment may not always have protoc installed.
// This file is intentionally checked in so that `go test ./...` can compile without requiring
// a local protoc toolchain.

package vehiclepb

import (
	reflect "reflect"
	sync "sync"

	proto "google.golang.org/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vehicle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PlateNumber   string                 `protobuf:"bytes,2,opt,name=plate_number,json=plateNumber,proto3" json:"plate_number,omitempty"`
	Vin           string                 `protobuf:"bytes,3,opt,name=vin,proto3" json:"vin,omitempty"`
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	OwnerId       string                 `protobuf:"bytes,5,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vehicle) Reset() {
	*x = Vehicle{}
	mi := &file_internal_api_proto_vehicle_vehicle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}
func (x *Vehicle) String() string { return protoimpl.X.MessageStringOf(x) }
func (*Vehicle) ProtoMessage()    {}
func (x *Vehicle) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_vehicle_vehicle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*Vehicle) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_vehicle_vehicle_proto_rawDescGZIP(), []int{0}
}
func (x *Vehicle) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}
func (x *Vehicle) GetPlateNumber() string {
	if x != nil {
		return x.PlateNumber
	}
	return ""
}
func (x *Vehicle) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}
func (x *Vehicle) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}
func (x *Vehicle) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}
func (x *Vehicle) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}
func (x *Vehicle) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}
func (x *Vehicle) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type UpsertVehicleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vehicle       *Vehicle               `protobuf:"bytes,1,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertVehicleRequest) Reset() {
	*x = UpsertVehicleRequest{}
	mi := &file_internal_api_proto_vehicle_vehicle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}
func (x *UpsertVehicleRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*UpsertVehicleRequest) ProtoMessage()    {}
func (x *UpsertVehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_vehicle_vehicle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*UpsertVehicleRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_vehicle_vehicle_proto_rawDescGZIP(), []int{1}
}
func (x *UpsertVehicleRequest) GetVehicle() *Vehicle {
	if x != nil {
		return x.Vehicle
	}
	return nil
}

type UpsertVehicleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vehicle       *Vehicle               `protobuf:"bytes,1,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertVehicleResponse) Reset() {
	*x = UpsertVehicleResponse{}
	mi := &file_internal_api_proto_vehicle_vehicle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}
func (x *UpsertVehicleResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*UpsertVehicleResponse) ProtoMessage()    {}
func (x *UpsertVehicleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_vehicle_vehicle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*UpsertVehicleResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_vehicle_vehicle_proto_rawDescGZIP(), []int{2}
}
func (x *UpsertVehicleResponse) GetVehicle() *Vehicle {
	if x != nil {
		return x.Vehicle
	}
	return nil
}

type GetVehicleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVehicleRequest) Reset() {
	*x = GetVehicleRequest{}
	mi := &file_internal_api_proto_vehicle_vehicle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}
func (x *GetVehicleRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*GetVehicleRequest) ProtoMessage()    {}
func (x *GetVehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_vehicle_vehicle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*GetVehicleRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_vehicle_vehicle_proto_rawDescGZIP(), []int{3}
}
func (x *GetVehicleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetVehicleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vehicle       *Vehicle               `protobuf:"bytes,1,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVehicleResponse) Reset() {
	*x = GetVehicleResponse{}
	mi := &file_internal_api_proto_vehicle_vehicle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}
func (x *GetVehicleResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*GetVehicleResponse) ProtoMessage()    {}
func (x *GetVehicleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_vehicle_vehicle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*GetVehicleResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_vehicle_vehicle_proto_rawDescGZIP(), []int{4}
}
func (x *GetVehicleResponse) GetVehicle() *Vehicle {
	if x != nil {
		return x.Vehicle
	}
	return nil
}

type ListVehiclesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVehiclesRequest) Reset() {
	*x = ListVehiclesRequest{}
	mi := &file_internal_api_proto_vehicle_vehicle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}
func (x *ListVehiclesRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*ListVehiclesRequest) ProtoMessage()    {}
func (x *ListVehiclesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_vehicle_vehicle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*ListVehiclesRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_vehicle_vehicle_proto_rawDescGZIP(), []int{5}
}
func (x *ListVehiclesRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}
func (x *ListVehiclesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}
func (x *ListVehiclesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListVehiclesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vehicles      []*Vehicle             `protobuf:"bytes,1,rep,name=vehicles,proto3" json:"vehicles,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVehiclesResponse) Reset() {
	*x = ListVehiclesResponse{}
	mi := &file_internal_api_proto_vehicle_vehicle_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}
func (x *ListVehiclesResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*ListVehiclesResponse) ProtoMessage()    {}
func (x *ListVehiclesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_vehicle_vehicle_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*ListVehiclesResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_vehicle_vehicle_proto_rawDescGZIP(), []int{6}
}
func (x *ListVehiclesResponse) GetVehicles() []*Vehicle {
	if x != nil {
		return x.Vehicles
	}
	return nil
}
func (x *ListVehiclesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_internal_api_proto_vehicle_vehicle_proto protoreflect.FileDescriptor

var file_internal_api_proto_vehicle_vehicle_proto_rawDescOnce sync.Once
var file_internal_api_proto_vehicle_vehicle_proto_rawDesc []byte

var file_internal_api_proto_vehicle_vehicle_proto_rawDescGZIPOnce sync.Once
var file_internal_api_proto_vehicle_vehicle_proto_rawDescGZIPData []byte

func file_internal_api_proto_vehicle_vehicle_proto_rawDescInit() []byte {
	file_internal_api_proto_vehicle_vehicle_proto_rawDescOnce.Do(func() {
		fd := buildVehicleFileDescriptorProto()
		b, _ := proto.Marshal(fd)
		file_internal_api_proto_vehicle_vehicle_proto_rawDesc = b
	})
	return file_internal_api_proto_vehicle_vehicle_proto_rawDesc
}

func file_internal_api_proto_vehicle_vehicle_proto_rawDescGZIP() []byte {
	file_internal_api_proto_vehicle_vehicle_proto_rawDescInit()
	file_internal_api_proto_vehicle_vehicle_proto_rawDescGZIPOnce.Do(func() {
		file_internal_api_proto_vehicle_vehicle_proto_rawDescGZIPData = protoimpl.X.CompressGZIP(file_internal_api_proto_vehicle_vehicle_proto_rawDesc)
	})
	return file_internal_api_proto_vehicle_vehicle_proto_rawDescGZIPData
}

var file_internal_api_proto_vehicle_vehicle_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_internal_api_proto_vehicle_vehicle_proto_goTypes = []any{
	(*Vehicle)(nil),               // 0: smartlinkdrive.vehicle.v1.Vehicle
	(*UpsertVehicleRequest)(nil),  // 1: smartlinkdrive.vehicle.v1.UpsertVehicleRequest
	(*UpsertVehicleResponse)(nil), // 2: smartlinkdrive.vehicle.v1.UpsertVehicleResponse
	(*GetVehicleRequest)(nil),     // 3: smartlinkdrive.vehicle.v1.GetVehicleRequest
	(*GetVehicleResponse)(nil),    // 4: smartlinkdrive.vehicle.v1.GetVehicleResponse
	(*ListVehiclesRequest)(nil),   // 5: smartlinkdrive.vehicle.v1.ListVehiclesRequest
	(*ListVehiclesResponse)(nil),  // 6: smartlinkdrive.vehicle.v1.ListVehiclesResponse
}

var file_internal_api_proto_vehicle_vehicle_proto_depIdxs = []int32{
	0, // 0: smartlinkdrive.vehicle.v1.UpsertVehicleRequest.vehicle:type_name -> smartlinkdrive.vehicle.v1.Vehicle
	0, // 1: smartlinkdrive.vehicle.v1.UpsertVehicleResponse.vehicle:type_name -> smartlinkdrive.vehicle.v1.Vehicle
	0, // 2: smartlinkdrive.vehicle.v1.GetVehicleResponse.vehicle:type_name -> smartlinkdrive.vehicle.v1.Vehicle
	0, // 3: smartlinkdrive.vehicle.v1.ListVehiclesResponse.vehicles:type_name -> smartlinkdrive.vehicle.v1.Vehicle
	0, // [0:4] is the sub-list for field type_name
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for method output_type
}

func init() { file_internal_api_proto_vehicle_vehicle_proto_init() }
func file_internal_api_proto_vehicle_vehicle_proto_init() {
	if File_internal_api_proto_vehicle_vehicle_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_api_proto_vehicle_vehicle_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Vehicle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_proto_vehicle_vehicle_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*UpsertVehicleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_proto_vehicle_vehicle_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*UpsertVehicleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_proto_vehicle_vehicle_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetVehicleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_proto_vehicle_vehicle_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetVehicleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_proto_vehicle_vehicle_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*ListVehiclesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_proto_vehicle_vehicle_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*ListVehiclesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}

	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_api_proto_vehicle_vehicle_proto_rawDescInit(),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_api_proto_vehicle_vehicle_proto_goTypes,
		DependencyIndexes: file_internal_api_proto_vehicle_vehicle_proto_depIdxs,
		MessageInfos:      file_internal_api_proto_vehicle_vehicle_proto_msgTypes,
	}.Build()
	File_internal_api_proto_vehicle_vehicle_proto = out.File
	file_internal_api_proto_vehicle_vehicle_proto_rawDesc = nil
	file_internal_api_proto_vehicle_vehicle_proto_rawDescGZIPData = nil
	file_internal_api_proto_vehicle_vehicle_proto_goTypes = nil
	file_internal_api_proto_vehicle_vehicle_proto_depIdxs = nil
}

func buildVehicleFileDescriptorProto() *descriptorpb.FileDescriptorProto {
	str := func(s string) *string { return &s }
	i32 := func(v int32) *int32 { return &v }
	label := func(v descriptorpb.FieldDescriptorProto_Label) *descriptorpb.FieldDescriptorProto_Label { return &v }
	typ := func(v descriptorpb.FieldDescriptorProto_Type) *descriptorpb.FieldDescriptorProto_Type { return &v }

	pkg := "smartlinkdrive.vehicle.v1"
	name := "internal/api/proto/vehicle/vehicle.proto"
	syntax := "proto3"

	vehMsg := &descriptorpb.DescriptorProto{
		Name: str("Vehicle"),
		Field: []*descriptorpb.FieldDescriptorProto{
			{Name: str("id"), Number: i32(1), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_STRING), JsonName: str("id")},
			{Name: str("plate_number"), Number: i32(2), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_STRING), JsonName: str("plateNumber")},
			{Name: str("vin"), Number: i32(3), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_STRING), JsonName: str("vin")},
			{Name: str("model"), Number: i32(4), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_STRING), JsonName: str("model")},
			{Name: str("owner_id"), Number: i32(5), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_STRING), JsonName: str("ownerId")},
			{Name: str("status"), Number: i32(6), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_STRING), JsonName: str("status")},
			{Name: str("created_at"), Number: i32(7), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_INT64), JsonName: str("createdAt")},
			{Name: str("updated_at"), Number: i32(8), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_INT64), JsonName: str("updatedAt")},
		},
	}

	upsertReq := &descriptorpb.DescriptorProto{
		Name: str("UpsertVehicleRequest"),
		Field: []*descriptorpb.FieldDescriptorProto{
			{Name: str("vehicle"), Number: i32(1), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_MESSAGE), TypeName: str(".smartlinkdrive.vehicle.v1.Vehicle"), JsonName: str("vehicle")},
		},
	}
	upsertResp := &descriptorpb.DescriptorProto{
		Name: str("UpsertVehicleResponse"),
		Field: []*descriptorpb.FieldDescriptorProto{
			{Name: str("vehicle"), Number: i32(1), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_MESSAGE), TypeName: str(".smartlinkdrive.vehicle.v1.Vehicle"), JsonName: str("vehicle")},
		},
	}
	getReq := &descriptorpb.DescriptorProto{
		Name: str("GetVehicleRequest"),
		Field: []*descriptorpb.FieldDescriptorProto{
			{Name: str("id"), Number: i32(1), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_STRING), JsonName: str("id")},
		},
	}
	getResp := &descriptorpb.DescriptorProto{
		Name: str("GetVehicleResponse"),
		Field: []*descriptorpb.FieldDescriptorProto{
			{Name: str("vehicle"), Number: i32(1), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_MESSAGE), TypeName: str(".smartlinkdrive.vehicle.v1.Vehicle"), JsonName: str("vehicle")},
		},
	}
	listReq := &descriptorpb.DescriptorProto{
		Name: str("ListVehiclesRequest"),
		Field: []*descriptorpb.FieldDescriptorProto{
			{Name: str("owner_id"), Number: i32(1), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_STRING), JsonName: str("ownerId")},
			{Name: str("page"), Number: i32(2), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_INT32), JsonName: str("page")},
			{Name: str("page_size"), Number: i32(3), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_INT32), JsonName: str("pageSize")},
		},
	}
	listResp := &descriptorpb.DescriptorProto{
		Name: str("ListVehiclesResponse"),
		Field: []*descriptorpb.FieldDescriptorProto{
			{Name: str("vehicles"), Number: i32(1), Label: label(descriptorpb.FieldDescriptorProto_LABEL_REPEATED), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_MESSAGE), TypeName: str(".smartlinkdrive.vehicle.v1.Vehicle"), JsonName: str("vehicles")},
			{Name: str("total"), Number: i32(2), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_INT64), JsonName: str("total")},
		},
	}

	svc := &descriptorpb.ServiceDescriptorProto{
		Name: str("VehicleService"),
		Method: []*descriptorpb.MethodDescriptorProto{
			{Name: str("UpsertVehicle"), InputType: str(".smartlinkdrive.vehicle.v1.UpsertVehicleRequest"), OutputType: str(".smartlinkdrive.vehicle.v1.UpsertVehicleResponse")},
			{Name: str("GetVehicle"), InputType: str(".smartlinkdrive.vehicle.v1.GetVehicleRequest"), OutputType: str(".smartlinkdrive.vehicle.v1.GetVehicleResponse")},
			{Name: str("ListVehicles"), InputType: str(".smartlinkdrive.vehicle.v1.ListVehiclesRequest"), OutputType: str(".smartlinkdrive.vehicle.v1.ListVehiclesResponse")},
		},
	}

	return &descriptorpb.FileDescriptorProto{
		Name:    &name,
		Package: &pkg,
		Syntax:  &syntax,
		Options: &descriptorpb.FileOptions{
			GoPackage: str("github.com/SmartLinkDrive/SmartLinkDrive/internal/api/proto/vehicle;vehiclepb"),
		},
		MessageType: []*descriptorpb.DescriptorProto{
			vehMsg,
			upsertReq,
			upsertResp,
			getReq,
			getResp,
			listReq,
			listResp,
		},
		Service: []*descriptorpb.ServiceDescriptorProto{svc},
	}
}
