// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/api/proto/user/user.proto
//
// NOTE: This repository's development environment may not always have protoc installed.
// This file is intentionally checked in so that `go test ./...` can compile without requiring
// a local protoc toolchain.

package userpb

import (
	reflect "reflect"
	sync "sync"

	proto "google.golang.org/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,3,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	Nickname      string                 `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Roles         []string               `protobuf:"bytes,7,rep,name=roles,proto3" json:"roles,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_internal_api_proto_user_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_user_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*User) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_user_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *User) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *User) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *User) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type RegisterUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserRequest) Reset() {
	*x = RegisterUserRequest{}
	mi := &file_internal_api_proto_user_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*RegisterUserRequest) ProtoMessage()    {}
func (x *RegisterUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_user_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_user_user_proto_rawDescGZIP(), []int{1}
}
func (x *RegisterUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}
func (x *RegisterUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}
func (x *RegisterUserRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}
func (x *RegisterUserRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}
func (x *RegisterUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type RegisterUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserResponse) Reset() {
	*x = RegisterUserResponse{}
	mi := &file_internal_api_proto_user_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*RegisterUserResponse) ProtoMessage()    {}
func (x *RegisterUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_user_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*RegisterUserResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_user_user_proto_rawDescGZIP(), []int{2}
}
func (x *RegisterUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_internal_api_proto_user_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}
func (x *LoginRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*LoginRequest) ProtoMessage()    {}
func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_user_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_user_user_proto_rawDescGZIP(), []int{3}
}
func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}
func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	User          *User                  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_internal_api_proto_user_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}
func (x *LoginResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*LoginResponse) ProtoMessage()    {}
func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_user_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_user_user_proto_rawDescGZIP(), []int{4}
}
func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}
func (x *LoginResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}
func (x *LoginResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_internal_api_proto_user_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}
func (x *GetProfileRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*GetProfileRequest) ProtoMessage()    {}
func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_user_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_user_user_proto_rawDescGZIP(), []int{5}
}

type GetProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	mi := &file_internal_api_proto_user_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}
func (x *GetProfileResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*GetProfileResponse) ProtoMessage()    {}
func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_user_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_user_user_proto_rawDescGZIP(), []int{6}
}
func (x *GetProfileResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_internal_api_proto_user_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}
func (x *ListUsersRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*ListUsersRequest) ProtoMessage()    {}
func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_user_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_user_user_proto_rawDescGZIP(), []int{7}
}
func (x *ListUsersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}
func (x *ListUsersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_internal_api_proto_user_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}
func (x *ListUsersResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*ListUsersResponse) ProtoMessage()    {}
func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_user_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_user_user_proto_rawDescGZIP(), []int{8}
}
func (x *ListUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}
func (x *ListUsersResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_internal_api_proto_user_user_proto protoreflect.FileDescriptor

var file_internal_api_proto_user_user_proto_rawDescOnce sync.Once
var file_internal_api_proto_user_user_proto_rawDesc []byte

var file_internal_api_proto_user_user_proto_rawDescGZIPOnce sync.Once
var file_internal_api_proto_user_user_proto_rawDescGZIPData []byte

func file_internal_api_proto_user_user_proto_rawDescInit() []byte {
	file_internal_api_proto_user_user_proto_rawDescOnce.Do(func() {
		fd := buildUserFileDescriptorProto()
		b, _ := proto.Marshal(fd)
		file_internal_api_proto_user_user_proto_rawDesc = b
	})
	return file_internal_api_proto_user_user_proto_rawDesc
}

func file_internal_api_proto_user_user_proto_rawDescGZIP() []byte {
	file_internal_api_proto_user_user_proto_rawDescInit()
	file_internal_api_proto_user_user_proto_rawDescGZIPOnce.Do(func() {
		file_internal_api_proto_user_user_proto_rawDescGZIPData = protoimpl.X.CompressGZIP(file_internal_api_proto_user_user_proto_rawDesc)
	})
	return file_internal_api_proto_user_user_proto_rawDescGZIPData
}

var file_internal_api_proto_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_internal_api_proto_user_user_proto_goTypes = []any{
	(*User)(nil),                 // 0: smartlinkdrive.user.v1.User
	(*RegisterUserRequest)(nil),  // 1: smartlinkdrive.user.v1.RegisterUserRequest
	(*RegisterUserResponse)(nil), // 2: smartlinkdrive.user.v1.RegisterUserResponse
	(*LoginRequest)(nil),         // 3: smartlinkdrive.user.v1.LoginRequest
	(*LoginResponse)(nil),        // 4: smartlinkdrive.user.v1.LoginResponse
	(*GetProfileRequest)(nil),    // 5: smartlinkdrive.user.v1.GetProfileRequest
	(*GetProfileResponse)(nil),   // 6: smartlinkdrive.user.v1.GetProfileResponse
	(*ListUsersRequest)(nil),     // 7: smartlinkdrive.user.v1.ListUsersRequest
	(*ListUsersResponse)(nil),    // 8: smartlinkdrive.user.v1.ListUsersResponse
}

var file_internal_api_proto_user_user_proto_depIdxs = []int32{
	0, // 0: smartlinkdrive.user.v1.RegisterUserResponse.user:type_name -> smartlinkdrive.user.v1.User
	0, // 1: smartlinkdrive.user.v1.LoginResponse.user:type_name -> smartlinkdrive.user.v1.User
	0, // 2: smartlinkdrive.user.v1.GetProfileResponse.user:type_name -> smartlinkdrive.user.v1.User
	0, // 3: smartlinkdrive.user.v1.ListUsersResponse.users:type_name -> smartlinkdrive.user.v1.User
	0, // [0:4] is the sub-list for field type_name
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for method output_type
}

func init() { file_internal_api_proto_user_user_proto_init() }
func file_internal_api_proto_user_user_proto_init() {
	if File_internal_api_proto_user_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_api_proto_user_user_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_proto_user_user_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*RegisterUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_proto_user_user_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*RegisterUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_proto_user_user_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*LoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_proto_user_user_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*LoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_proto_user_user_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GetProfileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_proto_user_user_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetProfileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_proto_user_user_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*ListUsersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_proto_user_user_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*ListUsersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}

	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_api_proto_user_user_proto_rawDescInit(),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_api_proto_user_user_proto_goTypes,
		DependencyIndexes: file_internal_api_proto_user_user_proto_depIdxs,
		MessageInfos:      file_internal_api_proto_user_user_proto_msgTypes,
	}.Build()
	File_internal_api_proto_user_user_proto = out.File
	file_internal_api_proto_user_user_proto_rawDesc = nil
	file_internal_api_proto_user_user_proto_rawDescGZIPData = nil
	file_internal_api_proto_user_user_proto_goTypes = nil
	file_internal_api_proto_user_user_proto_depIdxs = nil
}

func buildUserFileDescriptorProto() *descriptorpb.FileDescriptorProto {
	str := func(s string) *string { return &s }
	i32 := func(v int32) *int32 { return &v }
	label := func(v descriptorpb.FieldDescriptorProto_Label) *descriptorpb.FieldDescriptorProto_Label { return &v }
	typ := func(v descriptorpb.FieldDescriptorProto_Type) *descriptorpb.FieldDescriptorProto_Type { return &v }

	pkg := "smartlinkdrive.user.v1"
	name := "internal/api/proto/user/user.proto"
	syntax := "proto3"

	userMsg := &descriptorpb.DescriptorProto{
		Name: str("User"),
		Field: []*descriptorpb.FieldDescriptorProto{
			{Name: str("id"), Number: i32(1), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_STRING), JsonName: str("id")},
			{Name: str("username"), Number: i32(2), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_STRING), JsonName: str("username")},
			{Name: str("password_hash"), Number: i32(3), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_STRING), JsonName: str("passwordHash")},
			{Name: str("nickname"), Number: i32(4), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_STRING), JsonName: str("nickname")},
			{Name: str("phone"), Number: i32(5), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_STRING), JsonName: str("phone")},
			{Name: str("email"), Number: i32(6), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_STRING), JsonName: str("email")},
			{Name: str("roles"), Number: i32(7), Label: label(descriptorpb.FieldDescriptorProto_LABEL_REPEATED), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_STRING), JsonName: str("roles")},
			{Name: str("created_at"), Number: i32(8), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_INT64), JsonName: str("createdAt")},
			{Name: str("updated_at"), Number: i32(9), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_INT64), JsonName: str("updatedAt")},
		},
	}

	registerReq := &descriptorpb.DescriptorProto{
		Name: str("RegisterUserRequest"),
		Field: []*descriptorpb.FieldDescriptorProto{
			{Name: str("username"), Number: i32(1), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_STRING), JsonName: str("username")},
			{Name: str("password"), Number: i32(2), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_STRING), JsonName: str("password")},
			{Name: str("nickname"), Number: i32(3), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_STRING), JsonName: str("nickname")},
			{Name: str("phone"), Number: i32(4), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_STRING), JsonName: str("phone")},
			{Name: str("email"), Number: i32(5), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_STRING), JsonName: str("email")},
		},
	}

	registerResp := &descriptorpb.DescriptorProto{
		Name: str("RegisterUserResponse"),
		Field: []*descriptorpb.FieldDescriptorProto{
			{Name: str("user"), Number: i32(1), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_MESSAGE), TypeName: str(".smartlinkdrive.user.v1.User"), JsonName: str("user")},
		},
	}

	loginReq := &descriptorpb.DescriptorProto{
		Name: str("LoginRequest"),
		Field: []*descriptorpb.FieldDescriptorProto{
			{Name: str("username"), Number: i32(1), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_STRING), JsonName: str("username")},
			{Name: str("password"), Number: i32(2), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_STRING), JsonName: str("password")},
		},
	}

	loginResp := &descriptorpb.DescriptorProto{
		Name: str("LoginResponse"),
		Field: []*descriptorpb.FieldDescriptorProto{
			{Name: str("access_token"), Number: i32(1), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_STRING), JsonName: str("accessToken")},
			{Name: str("expires_at"), Number: i32(2), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_INT64), JsonName: str("expiresAt")},
			{Name: str("user"), Number: i32(3), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_MESSAGE), TypeName: str(".smartlinkdrive.user.v1.User"), JsonName: str("user")},
		},
	}

	getProfileReq := &descriptorpb.DescriptorProto{Name: str("GetProfileRequest")}

	getProfileResp := &descriptorpb.DescriptorProto{
		Name: str("GetProfileResponse"),
		Field: []*descriptorpb.FieldDescriptorProto{
			{Name: str("user"), Number: i32(1), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_MESSAGE), TypeName: str(".smartlinkdrive.user.v1.User"), JsonName: str("user")},
		},
	}

	listUsersReq := &descriptorpb.DescriptorProto{
		Name: str("ListUsersRequest"),
		Field: []*descriptorpb.FieldDescriptorProto{
			{Name: str("page"), Number: i32(1), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_INT32), JsonName: str("page")},
			{Name: str("page_size"), Number: i32(2), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_INT32), JsonName: str("pageSize")},
		},
	}

	listUsersResp := &descriptorpb.DescriptorProto{
		Name: str("ListUsersResponse"),
		Field: []*descriptorpb.FieldDescriptorProto{
			{Name: str("users"), Number: i32(1), Label: label(descriptorpb.FieldDescriptorProto_LABEL_REPEATED), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_MESSAGE), TypeName: str(".smartlinkdrive.user.v1.User"), JsonName: str("users")},
			{Name: str("total"), Number: i32(2), Label: label(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL), Type: typ(descriptorpb.FieldDescriptorProto_TYPE_INT64), JsonName: str("total")},
		},
	}

	svc := &descriptorpb.ServiceDescriptorProto{
		Name: str("UserService"),
		Method: []*descriptorpb.MethodDescriptorProto{
			{Name: str("RegisterUser"), InputType: str(".smartlinkdrive.user.v1.RegisterUserRequest"), OutputType: str(".smartlinkdrive.user.v1.RegisterUserResponse")},
			{Name: str("Login"), InputType: str(".smartlinkdrive.user.v1.LoginRequest"), OutputType: str(".smartlinkdrive.user.v1.LoginResponse")},
			{Name: str("GetProfile"), InputType: str(".smartlinkdrive.user.v1.GetProfileRequest"), OutputType: str(".smartlinkdrive.user.v1.GetProfileResponse")},
			{Name: str("ListUsers"), InputType: str(".smartlinkdrive.user.v1.ListUsersRequest"), OutputType: str(".smartlinkdrive.user.v1.ListUsersResponse")},
		},
	}

	return &descriptorpb.FileDescriptorProto{
		Name:    &name,
		Package: &pkg,
		Syntax:  &syntax,
		Options: &descriptorpb.FileOptions{
			GoPackage: str("github.com/SmartLinkDrive/SmartLinkDrive/internal/api/proto/user;userpb"),
		},
		MessageType: []*descriptorpb.DescriptorProto{
			userMsg,
			registerReq,
			registerResp,
			loginReq,
			loginResp,
			getProfileReq,
			getProfileResp,
			listUsersReq,
			listUsersResp,
		},
		Service: []*descriptorpb.ServiceDescriptorProto{svc},
	}
}
